# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e9f5d03940be0eba90e36b11ba2d73bd19da8df1d4fbd62c4852f5e54218e0e59c43f0ee4f43d32fee6ae811ba1ce6145dbe0c1c364b6b6240f771bac8415fd4

test:
  secret_key_base: 7a991dd20d7aa00c400d6614d5ba80e0a7750208c5bd4d087f7bfe5838a8a011358f82833a2de7bf6db02bd8ab09207b1d3f2eb3b0aeffb0e7480215aa429c48

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
